### ISSUE TITLE
Organazing repo and dir 1

### ISSUE THREAD

**Issue by ghost** [johanna-lud/Angular#1]
Please, next time if you creating a repo for code review create an empty repo first and then add the first pull-request. PR is really useful for code review, thank you!
I have some comments:
- logic on `ng-click` should not be present on views, please move it to the controller. But be aware that business logic should be in services;
- why you don't like indentation? it makes code easy readable;
- file organization - source code in one place, assets and static files in another;

**Comment by johanna-lud** [comment]
Fixed
